# Generated by Django 4.2.28 on 2026-02-10 12:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='District or area name', max_length=100)),
                ('region', models.CharField(choices=[('central', 'Central Region'), ('eastern', 'Eastern Region'), ('northern', 'Northern Region'), ('western', 'Western Region'), ('kampala', 'Kampala Metropolitan')], max_length=50)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('5000'), max_digits=10)),
                ('estimated_days', models.PositiveIntegerField(default=2, help_text='Estimated delivery days')),
                ('is_active', models.BooleanField(default=True)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=Decimal('100000'), help_text='Order amount for free delivery', max_digits=12)),
            ],
            options={
                'ordering': ['region', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('lg', 'Luganda'), ('sw', 'Kiswahili')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='momo_phone',
            field=models.CharField(blank=True, help_text='MTN/Airtel number for payments', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_payment_method',
            field=models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('paypal', 'PayPal')], default='mtn', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='receive_sms',
            field=models.BooleanField(default=True, help_text='Receive SMS notifications'),
        ),
        migrations.AddField(
            model_name='customer',
            name='receive_whatsapp',
            field=models.BooleanField(default=True, help_text='Receive WhatsApp updates'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='alternate_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='district',
            field=models.CharField(default='Kampala', max_length=100),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='gps_coordinates',
            field=models.CharField(blank=True, default='', help_text='lat,lng for delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='landmark',
            field=models.CharField(blank=True, default='', help_text='Nearby landmark for easy location', max_length=200),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='preferred_delivery_time',
            field=models.CharField(choices=[('morning', 'Morning (8AM-12PM)'), ('afternoon', 'Afternoon (12PM-5PM)'), ('evening', 'Evening (5PM-8PM)'), ('anytime', 'Anytime')], default='anytime', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Format: 0700000000', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(help_text='Street/Road, Building, etc.', max_length=300),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Special delivery instructions'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='region',
            field=models.CharField(default='Central Region', max_length=100),
        ),
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('state', models.CharField(choices=[('start', 'Start'), ('category_select', 'Selecting Category'), ('product_select', 'Selecting Product'), ('quantity_input', 'Entering Quantity'), ('confirm', 'Confirming Order'), ('payment', 'Payment'), ('complete', 'Complete')], default='start', max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order')),
                ('selected_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
                ('selected_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text='Phone number in format: 256700000000', max_length=15)),
                ('message', models.TextField(max_length=480)),
                ('notification_type', models.CharField(choices=[('order_confirmation', 'Order Confirmation'), ('payment_received', 'Payment Received'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('promotional', 'Promotional'), ('otp', 'OTP Verification')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gateway_message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('gateway_response', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_notifications', to='store.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_description', models.TextField(blank=True)),
                ('physical_address', models.TextField(blank=True)),
                ('gps_coordinates', models.CharField(blank=True, help_text='lat,lng format', max_length=50)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_payout_method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money')], default='mtn', max_length=20)),
                ('payout_phone', models.CharField(blank=True, max_length=15)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
                ('auto_accept_orders', models.BooleanField(default=True)),
                ('receive_sms_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to='store.customer')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.deliveryzone')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('first_order_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='MobileMoneyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money')], max_length=20)),
                ('phone_number', models.CharField(help_text='Format: 256700000000', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('external_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_payments', to='store.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkOrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('quantity', models.PositiveIntegerField()),
                ('preferred_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quote_valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('quoted', 'Quote Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('delivery_location', models.TextField()),
                ('preferred_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_requests', to='store.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='delivery_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.deliveryzone'),
        ),
    ]
